# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPoe():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_poe(self):
        self.driver.get("http://10.200.0.108/")
        self.driver.set_window_size(974, 780)
        self.driver.find_element(By.CSS_SELECTOR, ".material-input-focus .el-input__inner").click()
        self.driver.find_element(By.CSS_SELECTOR, ".material-input-focus .el-input__inner").send_keys("admin")
        self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").click()
        self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys("Sencore123")
        self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, ".is-active .el-menu-item:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".el-button--text:nth-child(2) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mt20 .el-checkbox__inner").click()
        self.driver.find_element(By.CSS_SELECTOR, ".el-switch__core").click()
        self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.close()

